###
#   File name : After_NetworkComparison_Cluster_Runs.R
#   Author    : Hyunjin Kim
#   Date      : Jan 6, 2019
#   Email     : hk2990@cumc.columbia.edu
#   Purpose   : After the cluster runs based on the scripts generated by
#               "ScriptsForClusters_NetworkComparison.R", we combine the result files
#               and draw MDS and hierarchical clustering plots based on the similarities.
#
#   Instruction
#               1. Source("After_NetworkComparison_Cluster_Runs.R")
#               2. Run the function "random_walk_all_networks_result" - specify the necessary input and output paths
#               3. The result file will be generated in the output path
#
#   Example
#               > source("The_directory_of_After_NetworkComparison_Cluster_Runs.R/After_NetworkComparison_Cluster_Runs.R")
#               > random_walk_all_networks_result(results_dir = "./results/network_comparison/all_62_tissues/",
#                                                 output_dir = "./results/network_comparison/all_62_tissues/similarity/")
###

random_walk_all_networks_result <- function(results_dir = "//isilon.c2b2.columbia.edu/ifs/archive/shares/af_lab/GTEx/network_comparison/all_62_tissues/",
                                            output_dir = "//isilon.c2b2.columbia.edu/ifs/archive/shares/af_lab/GTEx/network_comparison/all_62_tissues/similarity/") {
  
  ### get cluster run result files
  f <- list.files(path = results_dir, pattern = "\\.txt$")
  
  ### load cluster run results
  cluster_results <- vector("list", length = length(f))
  names(cluster_results) <- sapply(f, function(x) substr(x, 1, nchar(x)-4))
  for(tissue in names(cluster_results)) {
    cluster_results[[tissue]] <- read.table(file = paste0(results_dir, tissue, ".txt"),
                                          stringsAsFactors = FALSE, check.names = FALSE)
  }
  
  ### make a matrix with the results
  similarity_mat <- matrix(0, length(cluster_results), length(cluster_results))
  rownames(similarity_mat) <- names(cluster_results)
  colnames(similarity_mat) <- names(cluster_results)
  for(row in rownames(similarity_mat)) {
    for(col in colnames(similarity_mat)) {
      similarity_mat[row,col] <- cluster_results[[row]][col, 1]
    }
  }
  
  ### save the matrix
  write.table(similarity_mat, file = paste0(output_dir, "All_62_networks_random_walk_similarities.txt"),
              sep = "\t", row.names = TRUE)
  
  ### similarity to distance
  ### -log2(similarity) - min(-log2(similarity))
  similarity_mat2 <- -log2(similarity_mat)
  similarity_mat2 <- similarity_mat2 - min(similarity_mat2)
  
  ### distance calculation
  d <- as.dist(similarity_mat2)
  
  ### draw a MDS plot
  fit <- cmdscale(d, eig=TRUE, k=2)
  x_c <- fit$points[,1]
  y_c <- fit$points[,2]
  png(paste0(output_dir, "MDS_All_62_networks_random_walk_similarities.png"),
      width = 2000, height = 1500, res = 130)
  plot(x_c, y_c, main=paste0("MDS based on Random Walk Network Similarities"),	type="n")
  text(x_c, y_c, labels = labels(d), cex=.7, pos=3)
  dev.off()
  
  ### draw a hierarchical clustering
  png(paste0(output_dir, "Hclust_All_62_networks_random_walk_similarities.png"),
      width = 2000, height = 1500, res = 130)
  plot(hclust(d), main=paste0("Hierarchical Clustering based on Random Walk Network Similarities"),
       xlab = "", sub = "")
  dev.off()
  
}
