#!/bin/bash

# This code was used for submitting the production GO enrichment array job to the
# cluster. It sets up the output directories and submits the cluster  The following directories 
# were used:
# 	data/: contained the <tcga_acro>.rda interactome files, one each for the
#		TCGA interactome generated by ARACNe. Each such file contained an 
#		argument titled <tcga_acro> which was the one generated by my CPTAC code,
#		after processing Federico's original ARACNe files.
# 	runs/: this is where the output from the cluster jobs are stored. The script begins
#		by creating a directory titled <tcga_acro> for each tumor to be processed and 
#		creates there a link to the <tcga_acro>.rda file mentioned above. In each such
#		directory it creates a subdirectory titled "out" for stroring the stdout and stderr 
#		generated by the cluster jobs, the cds there (so that this "out" directory is the 
#		location from where the cluster job is submitted), and finally qsubs the array job.
#	scripts/: contains the current script as well as the script arrayRunGO.sh (see below) 
#		which is the job that will run on each individual CPU.

root="/ifs/scratch/c2b2/af_lab/floratos/CPTAC/"
nets="blca lgg skcm brca lihc stad coad luad thca gbm lusc ucec hnsc ov kirc prad kirp read laml sarc"
for net in $nets; do
	file=$root"data/"$net".rda"
	cd $root"runs/"
	mkdir $net
	cd $net
	ln $file $net".rda"
	mkdir out
	cd out
	
	# This is the array job submission, one for each interactome. Every array job requests 200 CPUs, 
	# each of which will run a chunk of the enrichment calculation comprising CHUNK regulons (for this
	# run CHUNK = 30). Each CPU is requested for a max of 2 hours and with a memory capacity of 2 GB.
	qsub -t 1-200:1 -l mem=2G,time=2:: -N GOenrichment -j yes -cwd -v NET=$net,ONT="BP",CHUNK="30" $root'scripts/arrayRunGO.sh'
done
