# *****************************************************************************
# Process the files generated by running the regulonGOenrichment.r script. The 
# latter performs GO enrichment analysis on the regulons of all the hubs in an
# interactome, processing hubs in groups of INC (in the "production" run, INC 
# was set to 30), generating one file for each such group. This code aggregates
# the results from the individual files, removing hubs enriched for no GO terms.
# For each interactome we generate a named list with one entry per hub gene G
# (entries are named with the Entrez ID of the hub gene) where the entry for G
# is the data frame Utils::goEnrichment(regulon(G))[[1]].
#
# The final lists are stored in a binary R file.
# *****************************************************************************

# Location of output generated by script regulonGOenrichment.r, stored in one
# directory per tumor iteractome processed.
ROOTDIR = "/ifs/archive/shares/bisr/Aris/cptac/"

# Names of directories where the analysis results are stored
netNames = c("blca", "lgg", "skcm", "brca", "lihc", "stad", "coad", "luad", "thca", "gbm", 
		"lusc", "ucec", "hnsc", "ov", "kirc", "prad", "kirp", "read", "laml", "sarc", "nbrca")

# Name of binary R file where to store results
resultFileName = "RegulonGOannotations.rda"

# README info, this method is stored in the results file, as a means of 
# self-documentation
READMEGO <- function(){
	writeLines("The file contains the results of running GO Terms emrichment analysis on the regulons of")
	writeLines("all TCGA tumor ARACNe interactomes as well as the TCGA interactome of the normal breast")
	writeLines("tissue. The following variables are included:")
	writeLines("---> <net>GO: This is a list with one element per hub gene from the TCGA interactome with")
	writeLines("acronym <net>. Entries are named with the Entrez ID of their corresonding hub gene. The entry ")
	writeLines("correspondig to hub gene G contains the matrix returned by the method Utils::goEnrichment() ")
	writeLines("which contains one row for each GO term found to be sigificantly enriched (at FDR < 0.05) in ")
	writeLines("genes that belong to the regulon of G (enrichment was run using the 'weight01' method and FET). G")
	writeLines("Only hub genes annotated to at least one GO term are incuded.")
	writeLines("---> nbrcaGO: Same as above but for regulons in the normal breast interactome.")
	writeLines("")
}


# *****************************************************************************
# Process the variables generated by the incremental runs of the script 
# regulonGOenrichment.r.
#
# ARGUMENT
# * varNames:	Character array comtaining the variable names storing the results
#		of the regulonGOenrichment.r runs.
#
# RETURN VALUE
# A list with one entry per hub gene, as described in the opening comments of this
# file.
# *****************************************************************************
getGoList <- function(varNames){
	L = mget(varNames, envir = globalenv())
	names = unlist(sapply(L, function(x){return(names(x))}))
	L = unlist(L, recursive = F)
	names(L) = names
	t = unlist(sapply(L, function(x){return(length(x) > 0 && nrow(x) > 0)}))
	L = L[which(t == TRUE)]
	return(L)
}

# Read in all annotation files
for (net in netNames){
	folder = paste(ROOTDIR, net, sep="")
	files = list.files(path = folder, pattern = "1.rda", full.names=TRUE)
	for (fName in files)
		load(fName)
	# Name of variable where to store results from the processing of interactome 'net'
	varName = paste(net, "GO", sep="")
	# Clean up the annotations lists for the regulon hubs by retaining only 
	# hub genes enriched for at least one GO term. The 'ls' method below
	# retrieves the names of the variables used by the incremental runs of
	# regulonGOenrichment.r runs to store the GO enrichment dataframes for the 
	# interactome 'net'
	assign(varName, getGoList(ls(pattern = paste("^", net, "Res", sep=""))))
}

# save to binary R object
varGOnames = paste(netNames, "GO", sep="")
save(list = c(varGOnames, "varGOnames", "READMEGO"), file=resultFileName)
